### ISSUE TITLE
Failed to resolve download link in Android Studio

### ISSUE THREAD

**Issue by william27a** [Eeshwar-Krishnan/PhotonFTC#7]
Failed to resolve download link in Android Studio. Can I get an updated link to put in my implementation in dependencies, please?

**Comment by Eeshwar-Krishnan** [comment]
implementation 'com.github.Eeshwar-Krishnan:PhotonFTC:v2.0.4'
	        
	      This doesn't work on 8.2

**Comment by william27a** [comment]
That doesn't work. What is 8.2 fwiw

**Comment by Eeshwar-Krishnan** [comment]
This has been fixed in the latest version of Photon, it was due to a jitpack compilation error.
